### ISSUE TITLE
might want to change default port so its above 1024

### ISSUE THREAD

**Issue by scottstensland** [aserg-ufmg/JSCity#6]
On linux any port < 1024 is privileged so requires root to execute the process.  
If you change your default port as defined in your file JSCity/js/config.json  :

{
        "porta": 800
}

to something reasonable like 8888
then we do not need to execute nodejs as root.
As is when I launch your server as a normal user I get ERROR

cd  JSCity/js 
node server.js 

Server Started.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:800
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (/home/stens/other_src/JSCity/js/server.js:280:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

which is fixed by using a port greater than 1024

cool project - good luck !!!

**Comment by malilovick** [comment]
Hi scottstensland thanks for the tip.  I changed the default port to 8888.
